### ISSUE TITLE
Interference with behaviour of standard search in sidebar

### ISSUE THREAD

**Issue by matabele** [tobibeer/tw5-appear#1]
@tobibeer 

Thought you might like to know: the 'appear' plugin seems to interfere with the operation of the standard search in the sidebar. The popup listing opens only if you click the down arrow (should open when a search term is entered or when clicking in the search box.)

**Comment by tobibeer** [comment]
Hi matabele, thanks for pointing out. @felixhayashi has already created an issue: https://github.com/tobibeer/tb5/issues/1 ...I'll leave both open, anyway, because it possibly concerns slightly more than just the appear widget.

**Comment by felixhayashi** [comment]
@tobibeer And I already thought it's my browser that is doing weird stuff ;)

**Comment by tobibeer** [comment]
fixed with https://github.com/tobibeer/tw5-appear/releases/tag/0.6.1
