### ISSUE TITLE
Installing this plugin disables hiding of sidebar

### ISSUE THREAD

**Issue by hegart-dmishiv** [tobibeer/tw5-appear#2]
Hi Tobias, while we've been making great use of your `<$appear>` widget plugin in the **{{DesignWrite}}** course, we've noticed that as soon as it gets installed in a TiddlyWiki, we can no longer hide the SideBar of that wiki. This is replicable by dragging/dropping your [$:/plugins/tobibeer/appear](https://tobibeer.github.io/tw5-plugins/#%24%3A%2Fplugins%2Ftobibeer%2Fappear) link to a new, fresh [empty.html](http://tiddlywiki.com/empty.html) file.

**Comment by tobibeer** [comment]
Hi @hegart-dmishiv, apologies for not having noticed this ticket and for the inconvenience.

This is fixed with the latest version **0.6.2**:
- http://tobibeer.github.io/tw5-plugins#appear
- https://github.com/tobibeer/tw5-appear/releases/tag/0.6.2
