### ISSUE TITLE
slidder - unfold all text

### ISSUE THREAD

**Issue by moxou** [tobibeer/tw5-appear#3]
Hello
I have many slider
` <$vars tid1="Noter les dégâts">
<$appear show="<$text text=<<tid1>>/>" $state="tiddler-slider" mode="block">
<$transclude mode="block" tiddler=<<tid1>>/>
</$appear>
</$vars>

 <$vars tid2="Effets des dégâts ordinaires">
<$appear show="<$text text=<<tid2>>/>" $state="tiddler-slider" mode="block">
<$transclude mode="block" tiddler=<<tid2>>/>
</$appear>
</$vars>

 <$vars tid3="Effets d’une blessure grave">
<$appear show="<$text text=<<tid3>>/>" $state="tiddler-slider" mode="block">
<$transclude mode="block" tiddler=<<tid3>>/>
</$appear>
</$vars>
`
But they all open/close at the same time and not separately

**Comment by tobibeer** [comment]
In TiddlyWiki, states need to be unique if you want things like sliders to behave independent of one another. If you use the very same parameters for your appear widgets, the auto-calculated states will be the same. I suggest you use unique $state identifiers for each instance.
