### ISSUE TITLE
Use in Headers

### ISSUE THREAD

**Issue by diego898** [tobibeer/tw5-appear#4]
If I try to use appear next to heading, allowing me to collapse the section, the entire section gets rendered as a header. The only way around this is to put the appear on a new line below the header, but its not as visually appealing.

**Comment by tobibeer** [comment]
@diego898 Quick test suggests you can achieve it using html syntax:

```
<$appear show="<h1>Heads up!</h1>">

Some content for you.</$appear>
```

**Comment by diego898** [comment]
Thanks tobias! This was very useful to me. It might be useful to add this as an example in appear-examples.

**Comment by tobibeer** [comment]
@diego898: on the todo list ;-)

**Comment by tobibeer** [comment]
@diego898, now that [my build is fixed](https://github.com/Jermolene/TiddlyWiki5/issues/3025), I added an example for ["HTML Markup" in buttons](http://tobibeer.github.io/tw5-plugins/#appear-Examples).

**Comment by diego898** [comment]
Thanks @tobibeer!!
